name: deploy_frontend

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
    secrets:
      npmrc: { required: true }
        

# defaults:
#   run:
#     working-directory: services/${{ inputs.app_name }}/client

jobs:
  child_build:
    env:
      NODE_VERSION: 18

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Set App Name
        run: |
          echo "aaa=npmrc" >> $GITHUB_ENV
      - name: echo aaa
        run: echo ${{ env.APP_NAME }}
      
      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@main
        with:
          files: test.yaml

      - name: Display read-yaml output
        run: echo "${{ env.A }}"

      
#       - run: echo ${{ inputs.app_name }}
#         working-directory: "${{ inputs.app_name }}"
      - run: echo ${{ secrets[env.aaa] }} | sed 's/./& /g'
      
      - run: echo "privet"
        if: ${{ env.NODE_VERSION == 18 }}
#         working-directory: ${{ github.workflow }}/client
