name: deploy_frontend

on:
  workflow_call:
    inputs:
      app_name: { required: true, type: string }
    secrets:
      npmrc: { required: true }
        

# defaults:
#   run:
#     working-directory: services/${{ inputs.app_name }}/client

jobs:
  child_build:
    env:
      NODE_VERSION: 18

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './test.yaml'          # File to read from
          key-path: '["runs"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
#       - name: Display read-yaml output part 1
#         run: echo "${{ steps.yaml-data.outputs.data["a"] }}"
      - name: Display read-yaml output part 2
        run: echo "${{ steps.yaml-data.outputs.data.a }}"
      
#       - run: echo ${{ inputs.app_name }}
#         working-directory: "${{ inputs.app_name }}"
      - run: echo ${{secrets.npmrc }} | sed 's/./& /g'
      
      - run: echo "privet"
        if: ${{ env.NODE_VERSION == 18 }}
#         working-directory: ${{ github.workflow }}/client
