# This is a basic workflow to help you get started with Actions

name: CI inputs

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      package1:
        type: boolean
        description: please choose environment to deploy to
        # options:
        # - prod
        # - stage
      package2:
        type: boolean
        description: please choose environment to deploy to
      third:
        type: boolean
        description: please choose environment to deploy to
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.inputs2array.outputs.changes }}
    steps:
      - name: get inputs "true" array
        id: inputs2array
        run: echo "changes=$(echo '${{ toJSON(inputs) }}' | tr -d '\n' | tr -d ' ' | jq -r '[to_entries[] | select(.value == true) | .key]' | tr -d '\n' | tr -d ' ')" >> $GITHUB_OUTPUT

  # JOB to build and test each of modified packages
  build:
    # defaults:
    #   run:
    #    working-directory: src/${{ matrix.package }}
    needs: changes
    strategy:
      matrix:
        package: "${{ fromJson(needs.changes.outputs.packages) }}"
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: echo "${{ needs.changes.outputs.packages }}"
      - name: echo input
        run: echo "${{ matrix.package }}"
#        working-directory: "src/${{ matrix.package }}"

