# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package1: src/package1/**
          package2: src/package2/**

  # JOB to build and test each of modified packages
  build:
    needs: changes
#     strategy:
#       matrix:
#         package: "${{ fromJSON(needs.changes.outputs.packages) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo "${{ needs.changes.outputs.packages }}"
