# This is a basic workflow to help you get started with Actions

name: my_ci_test_

on:
  push:
    branches: [ "main" ]
    paths:
      - "ci/**"
  workflow_dispatch:
    inputs:
      app_name:
        type: choice
        description: please choose environment to deploy to
        options:
        - prod
        - stage

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.setvars.outputs.app_name }}

    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            echo "app_name=dispatch" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.event_name}}" == "push" ]]; then
            echo "app_name=push" >> $GITHUB_OUTPUT
          fi

    
  call-workflow-passing-data:
    needs: init
    uses: yosefy/test-actions/.github/workflows/child.yaml@main
    with:
      app_name: "${{needs.init.outputs.app_name}}"
    secrets:
      npmrc: ${{ secrets[needs.init.outputs.app_name] }}
      
  local_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.workflow }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
