# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "ci/**"
  pull_request:
    branches: [ "main" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.setvars.outputs.app_name }}

    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            echo "app_name=dispatch" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.event_name}}" == "push" ]]; then
            echo "app_name=push" >> $GITHUB_OUTPUT
          fi
    
  call-workflow-passing-data:
    needs: init
    uses: yosefy/test-actions/.github/workflows/child.yaml@main
    with:
      app_name: "${{needs.init.outputs.app_name}}"
    secrets:
      npmrc: ${{ secrets[needs.init.outputs.app_name] }}
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo ${{ github.workflow }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
